DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS guitars;
DROP TABLE IF EXISTS dragons;
DROP TABLE IF EXISTS bands;
DROP TABLE IF EXISTS books;

CREATE TABLE songs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL
);

CREATE TABLE guitars (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  brand TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL
  
);

CREATE TABLE dragons (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  breed TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL
  
);

CREATE TABLE bands (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL
  
);

CREATE TABLE books (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  author TEXT,
  url TEXT NOT NULL
  
);

